version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: Authenticate
                command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - run:
                name: Publish to NPM
                command: npm publish

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /^v.*/
        - publish:
            requires:
              - build-and-test
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/